modLoader = "javafml"
loaderVersion = "[40,)"
license = "MIT License"
issueTrackerURL = "https://github.com/Mrthomas20121/ThermalExtra/issues"

[[mods]]
modId = "thermal_extra"
version = "1.0.7"
displayName = "Thermal: Extra"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/thermal_extra"
#logoFile="tinkers_reforged_logo.png"
credits = "Team CoFH"
authors = "Mrthomas20121"
description = '''
Add more augments to Thermal
'''

[[dependencies.thermal_extra]]
    modId = "forge"
    mandatory = true
    versionRange = "[40.1.19,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.thermal_extra]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.18.2,)"
    ordering = "NONE"
    side = "BOTH"